<?php
$Data=(array)json_decode(file_get_contents("php://input"));
//просто выдать токен и добавить его в бд + 4-значное число которое должен прислать пользователь
require_once "Validation/Validation.php";
require_once "Validation/message.php";




class MyValid extends Validation {
  // public function getTime(){}
    public function What_I_Must_do_if_all_is_cool()
    {
        echo "Done";
        //parent::What_I_Must_do_if_all_is_cool(); // TODO: Change the autogenerated stub
    }


}






//$Data=['phone'=>"12342","name"=>"asdfa"];
$db= new PDO("mysql:host=localhost;dbname=crud", "root","" );
$validaton=new MyValid();

$validaton->getConnectionToDb($db);

$data=$validaton->createNote($Data['phone'],300);
$data["name"]=$Data["name"];
$validaton->sendMessage(new message(),$data);